import React from "react";

const Terms = () => {
  return (
    <div className="fgi-legal-page">
      <div className="fgi-legal-card">
        <h1>Terms of Service</h1>
        <p className="fgi-legal-updated">Last updated: [Date]</p>

        <section>
          <h2>Acceptance of Terms</h2>
          <p>
            By accessing or using FillGap, you agree to be bound by these Terms
            of Service. If you do not agree, please do not use the platform.
          </p>
        </section>

        <section>
          <h2>Use of Service</h2>
          <p>
            FillGap is provided for personal, non-commercial interview
            preparation purposes. You agree not to misuse the platform, upload
            unlawful content, or attempt to abuse or overload our systems.
          </p>
        </section>

        <section>
          <h2>AI-Generated Content Disclaimer</h2>
          <p>
            Interview reports, questions, and roadmaps are generated by an AI
            model and are provided for guidance only. FillGap does not guarantee
            employment outcomes or the accuracy of AI-generated assessments.
          </p>
        </section>

        <section>
          <h2>Account Responsibility</h2>
          <p>
            You are responsible for maintaining the confidentiality of your
            account credentials and for all activity under your account.
          </p>
        </section>

        <section>
          <h2>Changes to Terms</h2>
          <p>
            We may update these Terms from time to time. Continued use of
            FillGap after changes constitutes acceptance of the revised Terms.
          </p>
        </section>

        <section>
          <h2>Contact</h2>
          <p>
            Questions about these Terms? Reach out via our <a href="/contact">Contact page</a>.
          </p>
        </section>
      </div>
    </div>
  );
};

export default Terms;